### ISSUE TITLE
There's a way to send payload to sentry ?

### ISSUE THREAD

**Issue by Elecweb** [hydra-newmedia/hapi-sentry#10]
For now, I can't find a way to send payload. it's indentation ? if not, I'm happy to open pull request.

if it's your indentation, I think it'd be great if you provide config for enable it. It might sound dangerous but sentry provide data scrubber that will try to get rid of sensitive information and we can also use `before-send` callback to get rid of sensitive by our own.

https://docs.sentry.io/data-management/sensitive-data/

or at least, provide a way to sending payload in specified route would be helpful.

**Comment by fiws** [comment]
This should be a workaround. I did not test it though.

```js
server.ext({
  type: 'onRequest',
  method(request, h) {
    request.sentryScope.setExtra('payload', request.payload);
    return h.continue;
  },
});
```

You can read about extending the hapi request lifecycle here: https://hapijs.com/api#-serverextevents
