### ISSUE TITLE
how can i use with a custom error

### ISSUE THREAD

**Issue by misaku** [hydra-newmedia/hapi-sentry#111]
i create a custom error and i use to change my response for example status 400 message user no found?
i can use sentry to capture this error for example

**Comment by fiws** [comment]
hi.

This is rather unusual as those error messages would usually swamp sentry on a public api. You could track sentry errors on the client to catch something like this.

But if you really need this for your use case, you could just capture a event by yourself before sending the custom error:

```js
const boom = require('boom');
const sentry = server.plugins['hapi-sentry'].client;

server.route({
  method: 'GET',
  path: '/your/route',
  handler(request) {
    const customError = boom.notFound('user not found');
    sentry.captureException(customError);

    return customError;
  },
});
```

If you need a generic solution you could probably use [hapi hooks](https://hapi.dev/api/?v=20.1.0#-serverextevents) and use `server.plugins['hapi-sentry'].client` in there to capture the error.


Please close it this solved your issue :)

**Comment by misaku** [comment]
@fiws  thx this resolve my problem =)
