### ISSUE TITLE
Documentation Question

### ISSUE THREAD

**Issue by framerate** [hydra-newmedia/hapi-sentry#118]
> Use request data and request.auth.credentials to enhance errors from routes

I just noticed this listed up top, however my errors (with a pretty bare bones install, passing my own Sentry Client when initialized) does not automatically get any enhancements from credentials.

Is this user error on my part (maybe out of date package)? Or is this documentation misleading and requires user to set it up?

Thanks!

**Comment by fiws** [comment]
Closing, feel free to reopen if you think there is a problem with the package.
