### ISSUE TITLE
Error attributes is required

### ISSUE THREAD

**Issue by rbudiharso** [hydra-newmedia/hapi-sentry#120]
When I include this plugin, Hapi server cannot start with error `"attributes" is required`. Looking trhough the source code indeed there is no `attributes` function required per [Hapi.js documentation](https://hapi.dev/api/?v=16.8.3#plugins)

![screenshot-20210820-141517](https://user-images.githubusercontent.com/43447/130195056-bff881c4-e76b-44ca-9f2d-56a90852de25.png)

**Comment by thomaspurchas** [comment]
@rbudiharso it looks like you're using Hapi v16 or earlier. This plugin only support Hapi V17 onwards. Hapi's internals were completely rewritten in V17, so it's not really possible to create plugin the supports both version simultaneously. I would strongly recommend upgrading to at least Hapi V17.

**Comment by rbudiharso** [comment]
Noted, closing this.
