### ISSUE TITLE
Inquiring about hapi v21.3.1 support

### ISSUE THREAD

**Issue by rlam3** [hydra-newmedia/hapi-sentry#141]
@fiws thank you for the hard work you've put into this project. 

my team and i are Inquiring about hapi v21.3.1 support and if there was going to be a release of the new version of this plugin soon. 

thank you!

**Comment by fiws** [comment]
Hi. You can use the pre-release `4.0.0-0` for now, which should support the latest hapi version. `-0` contains no breaking changes yet, though this might change with future versions.

I hope to have some time to properly update this repo soon..
