### ISSUE TITLE
Test failure in Sentry 7.73.0

### ISSUE THREAD

**Issue by joshkel** [hydra-newmedia/hapi-sentry#144]
The latest Sentry update (version 7.73.0) causes the ['allows deactivating capture (opts.dsn to be false)'](https://github.com/hydra-newmedia/hapi-sentry/blob/v4.0.0/test.mjs#L34) test to fail.

This is a result of https://github.com/getsentry/sentry-javascript/pull/9101 (which was added in order to support local processing of Sentry events, even if no transport / no DSN is configured).

I believe the test can simply be deleted (I believe it's safe to trust Sentry's behavior here), but I could be wrong.

**Comment by fiws** [comment]
sounds like setting it to "undefined" should work?

**Comment by joshkel** [comment]
@fiws , I'm not sure if that will work as intended:

Based on the README's documentation of `client`, I assumed that the [`opts.client.dsn !== undefined` check](https://github.com/hydra-newmedia/hapi-sentry/blob/v4.0.0/index.js#L15) is intended to distinguish between "an already initialized Sentry client" and "a Sentry client options object."

If the dsn is undefined, then hapi-sentry skips initializing Sentry completely. However, from skimming the rest of the hapi-sentry plugin, it looks like it assumes that Sentry is initialized.

**Comment by fiws** [comment]
fixed with 07eaac6ca1073db1036d6d19a2d14d0c10a788e1

test was adjusted to just test that "false" can still be passed
