### ISSUE TITLE
Updating to sentry@5

### ISSUE THREAD

**Issue by jardakotesovec** [hydra-newmedia/hapi-sentry#15]
Hi,
sentry@5 is now around for couple of weeks. Would you consider updating the dependency in hapi-sentry?

Here is [changelog](https://github.com/getsentry/sentry-javascript/releases/tag/5.0.0)

Thank you!

**Comment by fiws** [comment]
Looks like this is not a seamless update.

`Sentry.Parsers` which we use is gone. Its not mentioned in the changelog or migration guide.

Their [typedoc](http://getsentry.github.io/sentry-javascript/) also seems to be broken (at the time of writing), as its not displaying anything except the readme.
Will have to wait until at least their typedoc is working again.

**Comment by jardakotesovec** [comment]
Was addressed in #20 . Closing
