### ISSUE TITLE
Use package @hapi/hapi insted of hapi

### ISSUE THREAD

**Issue by autopilotfuturemind** [hydra-newmedia/hapi-sentry#24]
hapi package is deprecated https://www.npmjs.com/package/hapi

**Comment by guischdi** [comment]
Hi @autopilotfuturemind 
We are currently working on PR #21 which includes breaking changes. We will also switch the major version of the dependency on `@sentry/node` from 4 to 5. The dependency change you proposed also implies a major version bump on `hapi-sentry`. So we will publish all three changes as v2.x.x as soon as the PR is merged. We then will deprecate v1.x.x and v0.x.x.
So we apologize if it's taking a few days to get a new major on npm.

**Comment by mkg20001** [comment]
Hi @guischdi,
I took matters into my own hands ^^
Hope the PR works
https://github.com/hydra-newmedia/hapi-sentry/pull/26/files

**Comment by guischdi** [comment]
closed by #26

**Comment by fiws** [comment]
released in v2.0.0
