### ISSUE TITLE
Capturing request body: issue with snippet in docs

### ISSUE THREAD

**Issue by TyGuy** [hydra-newmedia/hapi-sentry#37]
Hello!

First off, thanks for maintaining this package! Very useful.

I was trying to set up my plugin to record the request body, [as mentioned here](https://github.com/hydra-newmedia/hapi-sentry#capturing-the-request-body). It seems to me like the given method doesn't actually work, because in the `onRequest` step, the `request.payload` is always `undefined` (payload processing hasn't taken place yet).

(My Hapi version is 17.9 ([lifecycle docs here](https://hapi.dev/api/?v=17.9.1#request-lifecycle)), but  from the docs [it looks like this applies to hapi v19 as well](https://hapi.dev/api/?v=19.0.5#request-lifecycle)).

I got this to work using the `onPostAuth` step. I'm not a Hapi expert, so I'm not 100% sure this is "the best" step; but it is working for me now.

Here are the contents of the plugin file I created, for reference:

```js
module.exports = {
  name: 'hapi-sentry-request-body',

  register: (server) => {
    server.ext('onPostAuth', (request, h) => {
      request.payload && request.sentryScope.setExtra('payload', request.payload);
      return h.continue;
    })
  }
}
```

Can the docs be updated to reflect using it in a different step (`onPostAuth` or whichever is best)?

**Comment by fiws** [comment]
hi. thanks for reporting this. Looks like you are correct. 

The new hapi docs (v19) even mention that `request.payload` will be undefined.

This should be fixed in the docs, but I'm not 100% sure which event we should advertise.

`onPostAuth` – which you are using – looks to be the earliest hook in the request lifecycle, so that might be the best. (but it looks a bit like a hack)

**Comment by fiws** [comment]
updated the readme with `onPostAuth`. capturing the body early probably is best if the request throws an error before reaching other stages.

Thanks again for reporting this.
