### ISSUE TITLE
Release 1.0.0

### ISSUE THREAD

**Issue by fiws** [hydra-newmedia/hapi-sentry#7]
We are testing `hapi-sentry` in production. I think we could release 1.0.0 if there are no issues with it in the next few days.

**Comment by guischdi** [comment]
I agree, will publish 1.0.0 tomorrow

**Comment by guischdi** [comment]
Done!

**Comment by bendrucker** [comment]
Thanks again guys! I've added a deprecation notice to [hapi-raven](https://github.com/bendrucker/hapi-raven) sending users here. Thanks again for putting this out and saving me the trouble of porting hapi-raven to the new SDK! 😄
