### ISSUE TITLE
Source code was not found for /app/node_modules/hapi/lib/handler.js

### ISSUE THREAD

**Issue by fiws** [hydra-newmedia/hapi-sentry#9]
maybe we should test this with a clean hapi project and see if we still get this error in sentry.

it happened for every error sent by hapi-sentry until now. (it also happened with hapi-raven I think)

it looks like this in sentry:

![image](https://user-images.githubusercontent.com/3409958/49096051-03435680-f26a-11e8-856b-f814019c44a5.png)

## upstream bug

https://github.com/getsentry/sentry-javascript/issues/1785

**Comment by tamtamchik** [comment]
Same issue. Not sure if it was before.

**Comment by guischdi** [comment]
I just reproduced this issue without even using `hapi-sentry` or `hapi`. The following minimal code example also re-produces the parsing error:
```JavaScript
const Sentry = require('@sentry/node');

Sentry.init({ dsn: 'https://5d29[...]58f@sentry.io/13[...]6' });

(async () => {
  const sentryEvent = await Sentry.Parsers.parseError(new Error('Test'));
  Sentry.captureEvent(sentryEvent);
})();
```

See https://github.com/getsentry/sentry-javascript/issues/1785

**Comment by maxmaier** [comment]
Schönen Sonntag! Ich verlass jetzt mal das Projekt!

**Comment by mkg20001** [comment]
Is this possibly fixed with #26 ?

**Comment by fiws** [comment]
No, I don't think so. Still got the warning with a test error.

**Comment by thomaspurchas** [comment]
@fiws this looks like a Sentry bug, not a plugin bug.

https://github.com/getsentry/sentry-javascript/issues/1785#issuecomment-599488197

**Comment by fiws** [comment]
> @fiws this looks like a Sentry bug, not a plugin bug.
> 
> [getsentry/sentry-javascript#1785 (comment)](https://github.com/getsentry/sentry-javascript/issues/1785#issuecomment-599488197)

indeed. we opened that bug with sentry.

This is a tracking bug now. We also need to check if this is still happening.

**Comment by fiws** [comment]
Looks like this has been fixed at some point. We no longer saw this in sentry for some time.
